name: Automacao BotConversa

on:
  schedule:
    - cron: '0 * * * *'  # Roda a cada hora na nuvem

  workflow_dispatch:
    inputs:
      acao:
        description: 'Qual ação deseja executar no BotConversa?'
        required: true
        default: 'start'
        type: choice
        options:
          - start
          - stop
      dias_semana:
        description: 'Quais dias da semana deve rodar?'
        required: true
        default: 'seg_a_sab'
        type: choice
        options:
          - 'seg_a_sab'
          - 'seg,ter,qua,qui,sex'
          - 'todos'
          - 'fim_de_semana'
      horario_inicio:
        description: 'Horário de Início (Horário do Brasil - Ex: 08)'
        required: true
        default: '08'
      horario_pausa:
        description: 'Horário de Pausa (Horário do Brasil - Ex: 18)'
        required: true
        default: '18'
      forcar_execucao:
        description: 'Ignorar checagem de dia/horário e executar agora?'
        required: true
        default: true
        type: boolean

jobs:
  executar:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar codigo
        uses: actions/checkout@v4.2.2

      - name: Configurar Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install playwright
          playwright install --with-deps chromium

      - name: Executar Automacao com Parametros do Formulario
        env:
          TZ: "America/Sao_Paulo"
          BOT_EMAIL: ${{ secrets.BOT_EMAIL }}
          BOT_SENHA: ${{ secrets.BOT_SENHA }}
          PARAM_ACAO: ${{ inputs.acao }}
          PARAM_DIAS: ${{ inputs.dias_semana }}
          PARAM_INICIO: ${{ inputs.horario_inicio }}
          PARAM_PAUSA: ${{ inputs.horario_pausa }}
          PARAM_FORCAR: ${{ inputs.forcar_execucao }}
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "Execução manual via formulário interativo."
            python bot.py "$PARAM_ACAO" "$PARAM_DIAS" "$PARAM_FORCAR" "$PARAM_INICIO" "$PARAM_PAUSA"
          else
            echo "Execução automática via agendamento."
            # Define o horário comercial padrão das 08h às 18h
            python bot.py "auto" "seg_a_sab" false "08" "18"
          fi
